export const GET_COUNTRIES = "GET_COUNTRIES";
export const FIND_COUNTRY = "FIND_COUNTRY";
export const ORDER_BY_NAME = "ORDER_BY_NAME";
export const ORDER_BY_POPULATION = "ORDER_BY_POPULATION";
export const FILTER_BY_ACTIVITY = "FILTER_BY_ACTIVITY";
export const FILTER_BY_CONTINENT = "FILTER_BY_CONTINENT";
export const POST_ACTIVITY = "POST_ACTIVITY";
export const GET_DETAIL = "GET_DETAIL";
